spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:jdbc:h2:tcp://localhost:9092/PoleLinguistic
    username: ADMIN
    password: pass

  h2:
    console:
      enabled: true
      path: /h2